#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

#define error(x) { puts(x); fclose(f); if (of) fclose(of); free(provs); free(counties); return 1; }

struct county
{
	uint8_t r,g,b;
	uint16_t pid;
	char name[27];
};

uint16_t colours[256][256][256];
char buffer[1024];

int main()
{
	FILE * f, * of = 0;
	int num_county, num_prov;
	int16_t * provs;
	struct county * counties;

	if (! (f = fopen("merge_baronies.tmp", "r")))
	{
		puts("Can't open merge_baronies.tmp");
		return -2;
	}

	fscanf(f, "%d %d", &num_county, &num_prov);

	if (! (provs = calloc(num_prov+1, 2)))
	{
		puts("Can't allocate memory for provinces.");
		fclose(f);
		return -1;
	}
	if (! (counties = calloc(num_county, 32)))
	{
		puts("Can't allocate memory for counties.");
		free(provs);
		fclose(f);
		return -1;
	}

	for (int i=0; i<num_county; ++i)
	{
		int num_bar;
		fscanf(f, "%26s %d", &counties[i].name[0], &num_bar);
		for (int j=0; j<num_bar; ++j)
		{
			int prov_num;
			fscanf(f, "%d", &prov_num);
			provs[prov_num] = i;
		}
	}

	fclose(f);

	if (! (f = fopen("definition.tmp", "r")))
	{
		puts("Can't open definition.tmp");
		free(counties);
		free(provs);
		return -2;
	}

	for (int i=0; i<=num_prov; ++i)
	{
		int prov_num, r, g, b;
		fscanf(f, "%d;%d;%d;%d;%[^\n]1023s", &prov_num, &r, &g, &b, &buffer[0]);
		colours[r][g][b] = prov_num;
		counties[provs[prov_num]].r = r;
		counties[provs[prov_num]].g = g;
		counties[provs[prov_num]].b = b;
		counties[provs[prov_num]].pid = prov_num;
	}

	fclose(f);

	if (! (f = fopen("output.csv", "w")))
	{
		puts("Can't open output.csv");
		free(counties);
		free(provs);
		return -2;
	}

	fprintf(f, "#This file generated by merge_baronies.c\n");
	for (int i=0; i<num_county; ++i)
		fprintf(f, "%d;%d;%d;%d;%s;x;\n", counties[i].pid, counties[i].r, counties[i].g, counties[i].b, counties[i].name);

	fclose(f);

	if (! (f = fopen("provinces.bmp", "rb")))
	{
		puts("Can't open provinces.bmp");
		free(counties);
		free(provs);
		return -2;
	}

	uint16_t signature, width, height, depth;
	uint32_t offset, size;

	if (1 != fread(&signature, 2, 1, f))
		error("Cannot read file.");
	if (signature != 0x4D42)
		error("File not bitmap.");
	if (fseek(f, 8, SEEK_CUR))
		error("Cannot seek file.");
	if (1 != fread(&offset, 4, 1, f))
		error("Cannot read file.");
	if (offset > 1024)
		error("Header too large.");
	if (1 != fread(&size, 4, 1, f))
		error("Cannot read file.");
	if (size < 40)
		error("Unsupported bitmat header.");
	if (1 != fread(&width, 4, 1, f))
		error("Cannot read file.");
	if (1 != fread(&height, 4, 1, f))
		error("Cannot read file.");
	if (fseek(f, 2, SEEK_CUR))
		error("Cannot seek file.");
	if (1 != fread(&depth, 2, 1, f))
		error("Cannot read file.");
	if (width != 8192 || height != 4096 || depth != 24)
		error("Unexpected image dimensions.");

	/* Okay, file format is okay, now open output file, copy the header, and convert while read/write. */
	if (! (of = fopen("output.bmp", "wb")))
		error("Cannot open output.bmp");
	if (fseek(f, 0, SEEK_SET))
		error("Cannot seek file.");
	if (1 != fread(&buffer[0], offset, 1, f))
		error("Cannot read file.");
	if (1 != fwrite(&buffer[0], offset, 1, of))
		error("Cannot write file.");

	for (int i = 0; i < width*height; ++i)
	{
		int r, g, b;
		if (1 != fread(&b, 1, 1, f))
			error("Cannot read file.");
		if (1 != fread(&g, 1, 1, f))
			error("Cannot read file.");
		if (1 != fread(&r, 1, 1, f))
			error("Cannot read file.");

		if (colours[r][g][b] > num_prov)
			error("Province index too high.");
		if (provs[colours[r][g][b]])
		{
			struct county c = counties[provs[colours[r][g][b]]];
			r = c.r;
			g = c.g;
			b = c.b;
		}

		if (1 != fwrite(&b, 1, 1, of))
			error("Cannot write file.");
		if (1 != fwrite(&g, 1, 1, of))
			error("Cannot write file.");
		if (1 != fwrite(&r, 1, 1, of))
			error("Cannot write file.");
	}

	fclose(of);
	fclose(f);
	free(counties);
	free(provs);
	remove("merge_baronies.tmp");
	remove("definition.tmp");
	return 0;
}

